name: Machines
description: A project for the Devathon contest
version: 1.0.0
author: Voronwe

main: org.devathon.contest2016.DevathonPlugin

commands:
  get:
    aliases: [roll, randomtile]
  info:
  create:
    aliases: [place]
  buy:
    aliases: [buymachines]
